on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4  # Update to a version that supports Node.js 20
        with:
          ref: main  # Specify the branch explicitly if needed

      - name: Use Node.js 20
        uses: actions/setup-node@v2.5.1  # Update to a version that supports Node.js 20
        with:
          node-version: '20'
      
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build --prod
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build  # Adjust as per your build directory
